data:
  dataset_name: lego
  path: data/blender/lego/train/*.png
  fid_file: data/blender/lego/fid_files/lego_256.npz
  img_size: 256
model:
  background_generator_kwargs:
    rgb_out_dim: 256
  bounding_box_generator_kwargs:
    scale_range_min: [0.2, 0.16, 0.16]
    scale_range_max: [0.25, 0.2, 0.2]
    translation_range_min: [-0.22, -0.12, 0.]
    translation_range_max: [0.22, 0.12, 0.]
    z_level_plane: 0.05
    object_on_plane: True
  generator_kwargs:
    range_v: [0.41667, 0.5]
    fov: 15
  neural_renderer_kwargs:
    input_dim: 256
    n_feat: 256
  decoder_kwargs:
    rgb_out_dim: 256
training:
  out_dir:  out/lego256
  learning_rate: 0.00025
rendering:
  render_dir: rendering
  render_program: [ 'render_camera_rotation','render_camera_elevation' ]